### ISSUE TITLE
Null point exception in tempToDrawable

### ISSUE THREAD

**Issue by tibnor** [tibnor/OpenAndroidWeather#13]
Stack trace from developer console
java.lang.NullPointerException
at no.firestorm.misc.TempToDrawable.getDrawableFromTemp(TempToDrawable.java:140)
at no.firestorm.weathernotificatonservice.WeatherNotificationService$ShowTempAsync.onPostExecute(WeatherNotificationService.java:154)
at android.os.AsyncTask.finish(AsyncTask.java:417)
at android.os.AsyncTask.access$300(AsyncTask.java:127)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:143)
at android.app.ActivityThread.main(ActivityThread.java:4196)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)

**Comment by tibnor** [comment]
due to wrong number from wsklima:

```
name=77005   77005   -99999.0    <null>  2011-06-11 15:00:00
```

**Comment by tibnor** [comment]
Solved serverside
